'CollageIsPremiumFeatureApplied': 'CIPFA',
'CollageLayoutDescription': 'CLD',
'CollageStateAspect': 'CSA',
'CollageStateBColor': 'CSBCo',
	'B': 'B',
	'G': 'G',
	'R': 'R',
'CollageStateGColor': 'CSCo',
'CollageStateGColorSecond': 'CSGCo',
'CollageStateInnerB': 'CSIB',
'CollageStateIsRotated': 'CSIR',
'CollageStateIsShapeLayout': 'CSISL',
'CollageStateIsZorder': 'CSIZ',
'CollageStateLayoutTag': 'CSLT',
'CollageStateOpacityShadow': 'CSOS',
'CollageStateOuterB': 'CSOB',
'CollageStateRoundM': 'CSRM',
'CollageStateShadowBlur': 'CSSB',
'CollageStateShadowColor': 'CSSCo',
'CollageStateXOffsetShadow': 'CSXOS',
'CollageStateYOffsetShadow': 'CSYOS',
'CollageStickerDescription': 'CSD',
'CollageStyleApplied': 'CStA',
'CollageTextDescription': 'CTD',
'CollageStatePattenImage': 'CSPat',
'CollageStateGCells':'CSGC',
'CellStateBackgroundFlag':'CSBF',
'CellStateCellMask':'CSMask',
	'POINT0x':'P0x',
	'POINT0y':'P0y',
	'TYPE':'TP',
	'POINT1x':'P1x',
	'POINT1y':'P1y',
	'POINT2x':'P2x',
	'POINT2y':'P2y',
'CellStateImageRotation':'CSIR',
'CellStateNCFrame':'CSNCF',
	'h':'h',
	'w':'w',
	'x':'x',
	'y':'y',
'CellStateRotationAngle':'CSRA',
'CellStateSuperViewIndexOfSubview':'CSVIS',
'CellStateViewProps':'CSVP',
'ZOOM_SCALE':'ZScl',
'CellStateZorder':'CSZ',
'gridCellMirror':'GCM',
'gridCellSync':'GCS',
'gridCellType':'GCT',
'gridCellVector':'GCV',
'CollageStateSticker':'CSS',
'StickerStateNCFrame':'SSNCF',
	'h':'h',
	'w':'w',
	'x':'x',
	'y':'y',
'StickerStatePreviousPanPoint':'SPanP',
'StickerStatePreviousRotation':'SSPR',
'StickerStatePreviousScale':'SSPS',
'StickerStateRotationAngle':'SSRA',
'StickerStateScale':'SSSCL',
'StickerStateStickerCustomSticker':'SCusS',
'StickerStateStyle':'SSSt',
'StickerStateZorder':'SSZ',
'CollageStateText':'CST',
'TextStateAlignment':'TSA',
'TextStateColor':'TSCo',
	'B':'B',
	'G':'G',
	'R':'R',
'TextStateColorIdentifier':'TSCI',
'TextStateContent':'TSC',
'TextStateFont':'TSF',
'TextStateIsModelDirty':'TSMD',
'TextStateNCFrame':'TSNCF',
	'h':'h',
	'w':'w',
	'x':'x',
	'y':'y',
'TextStateOpacity':'TSO',
'TextStatePreviousPanPoint':'TSPanP',
'TextStatePreviousRotation':'TSPR',
'TextStatePreviousScale':'TSPS',
'TextStateRotationAngle':'TSRA',
'TextStateScale':'TSS',
'TextStateStrokeColor':'TSSCo',
'TextStateStrokeWidth':'TSSW',
'TextStateStyle':'TSSt',
'TextStateZorder':'TSZ'