d={
	'CollageIsPremiumFeatureApplied': 'CIPFA',
	'CollageLayoutDescription': 'CLD',
	'CollageStateAspect': 'CSA',
	'CollageStateBColor': 'CSBCo',
	'B': 'B',
	'G': 'G',
	'R': 'R',
	'CollageStateGColor': 'CSCo',
	'CollageStateGColorSecond': 'CSGCo',
	'CollageStateInnerB': 'CSIB',
	'CollageStateIsRotated': 'CSIR',
	'CollageStateIsShapeLayout': 'CSISL',
	'CollageStateIsZorder': 'CSIZ',
	'CollageStateLayoutTag': 'CSLT',
	'CollageStateOpacityShadow': 'CSOS',
	'CollageStateOuterB': 'CSOB',
	'CollageStateRoundM': 'CSRM',
	'CollageStateShadowBlur': 'CSSB',
	'CollageStateShadowColor': 'CSSCo',
	'CollageStateXOffsetShadow': 'CSXOS',
	'CollageStateYOffsetShadow': 'CSYOS',
	'CollageStickerDescription': 'CSD',
	'CollageStyleApplied': 'CStA',
	'CollageTextDescription': 'CTD',
	'CollageStatePattenImage': 'CSPat'
}